language: clojure
lein: lein2
before_install:
- wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
- tar xzf dynamodb_local_latest.tar.gz
- java -jar DynamoDBLocal.jar &
script: lein2 test hildebrand.test.core hildebrand.test.channeled hildebrand.test.internal.request
  hildebrand.test.streams hildebrand.test.streams.channeled hildebrand.test.internal.response
env:
  global:
  - LOCAL_DYNAMO_URL=http://localhost:8000
  - secure: JyBnDXd3pqdxRanGwFUbHyx7D+3R8TOHxY2TK6gNEIlYw7qRUfdyXJiGaSJenJ6U8ajnFjA1xKViIrM/z5TbmqPxgsFpI7UswXP0mT8oSjbvqhql8DQ+vZG83coH/pnlXP1BBDWfC2+9fB7tgU6AnwmUvmjke2ykzwXWTpodtdE=
  - secure: O7UU+KjyV1rz8StBm9ceRjezroHQPyGNMqb2l1RhebZNnCpALzFfDxU0F8kY0ZVlnDAfgWG1kKb5SOuzNI5FD3XPj7LjHrTS+pkFDLnmRKOmXJOEJgbFOIZRQ7iaKRuyN11Aij5DZRkKnehc2YK1YrEL41m19qukqghqBr7Ah2I=
